# -*- coding: utf-8 -*-
"""parcial 2 programacion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17lOAd74QFDoJOuKhBMAqPZ5QIV17V3I0
"""

from google.colab import drive
import pandas as pd
drive.mount('/content/drive')
file_path = '/content/drive/My Drive/ABC - Sales.tex'
ventas = pd.read_csv(file_path)

ventas.head(12)

ventas.tail(15)

StoreLoc = ventas['store_location']

IdComprador = ventas['cust_id']

IdVenta = ventas['sale_id']

StoreLoc.sort_values(ascending=False)

IdComprador.sort_values(ascending=False)

IdVenta.sort_values(ascending=False)

nombres_columnas = ['product', 'qty', 'store_location']
columnas = ventas[nombres_columnas]

print(columnas)

ventas.isnull().sum()

productos_vendidos = ventas.groupby('product')['qty'].sum()

print(productos_vendidos)

ventas.groupby('prod_id')['qty'].sum()

ventas.sort_values(by='prod_id')

ventas.sort_values(by='cust_id')

ventas.sort_values(by=['cust_id', 'prod_id'])

ventas.sort_index(ascending=False)

ventasOptimizado = ventas.drop_duplicates()
ventasOptimizado

mi_lista = [1, 2, 3, 4, 5]
mi_serie = pd.Series(mi_lista)
mi_serie

mi_diccionario = {'col1': [1, 2, 3], 'col2': [4, 5, 6]}
mi_dataframe = pd.DataFrame(mi_diccionario)
mi_dataframe